### PR TITLE
fix: trim trailing slashes on `url` for multi-segment patterns

### LINKED ISSUE #5: Ending slash is output for pattern without ending slash
Hi! I decided to build own router and stuck on small mismatch with path-to-regexp behaviour.

I expect `/:page` matching `/dashboard/activities` do not include slash in the end of dashboard in exec array.
https://codesandbox.io/s/intelligent-fermat-mwv42

### PR DESCRIPTION
**Pull request by lukeed**
- Closes #5

### CODE REVIEW

File: test/index.js [hunk 1]
```diff
@@ -11,6 +11,10 @@ function run(route, url, loose) {
   return out;
 }
 
+function raw(route, url, loose) {
```
Comment (TrySound) [inline test/index.js]: Two separate functions `exact` and `loose` may improve readability.

Comment (lukeed) [reply test/index.js]: Maybe another time :) This helped legibility for me now while covering my tracks
